kind: pipeline
name: test on arm64

platform:
  arch: arm64

steps:
- name: test
  image: quay.io/condaforge/mambaforge:latest
  environment:
    MATPLOTLIB: agg
  commands:
    - lscpu
    - mamba install hyperspy-base --only-deps
    - mamba install scikit-learn pytest pytest-xdist
    # Need rosettasciio
    - pip install https://github.com/hyperspy/rosettasciio/archive/refs/heads/main.zip
    - pip install -e .
    - pytest -n 4

