# For details: https://github.com/ericpre/ci-scripts
language: python

env:
  global:
    - ENV=pip
    - PIP_SELECTOR="all, tests"
    - PYTEST_ARGS="--pyargs hyperspy --cov=hyperspy"

matrix:
  include:
  - name: "Linux, 3.8, pip"
    env: export PIP_SELECTOR="dev"
    python: 3.8
  - name: "Linux, 3.7, pip"
    env: export PIP_SELECTOR="dev"
    python: 3.7
  - name: "Linux, 3.7, pip, minimum environment"
    env: export PIP_SELECTOR="dev"
    python: 3.7
  - name: "Linux, 3.7, pip, doc"
    env: export PIP_SELECTOR="build-doc"
    python: 3.7
  - name: "Linux, 3.6, pip"
    env: export PIP_SELECTOR="dev"
    python: 3.6

before_install:
  # Clone the ci-scripts repo to get the ci setup scripts
  - git clone --depth 1 git://github.com/ericpre/ci-scripts.git
  - source ci-scripts/travis/setup_travis.sh

install:
  # Install the package
  - pip install --upgrade -e .["${PIP_SELECTOR}"]

script:
  - which python
  - python -c 'import matplotlib.pyplot as plt; print("Matplotlib backend:", plt.get_backend())';
  - if [ $PIP_SELECTOR == "build-doc" ]; then
      cd doc && make html;
    else
      pytest $PYTEST_ARGS;
    fi

after_success:
- coveralls
- python setup.py bdist_wheel sdist;

before_deploy:
- export DISTRIB=$(ls ./dist/*);

deploy:
  provider: releases
  api_key:
    # Add the secure key created and set in the travis account settings
    secure: # For example ${GITHUB_TOKEN_ERICPRE}
  file: "${DISTRIB}"
  skip_cleanup: true
  on:
    tags: true
    condition: $ENV = pip
