# For details: https://github.com/ericpre/ci-scripts
language: python

env:
  global:
    - ENV=pip
    - PIP_SELECTOR="all, tests, coverage"
    - PYTEST_ARGS="--pyargs hyperspy"
    - MINIMUM_VERSION=false

matrix:
  include:
  - name: "Linux, 3.8, pip"
    python: 3.8
  - name: "Linux, 3.7, pip"
    python: 3.7
    env: PYTEST_ARGS="--pyargs hyperspy --cov=hyperspy"
  - name: "Linux, 3.6, pip"
    python: 3.6
  - name: "Linux, 3.7, pip, minimum requirement"
    env: PIP_SELECTOR="tests"
    python: 3.7
  - name: "Linux, 3.6, pip, mininum version"
    env: MINIMUM_VERSION=true
    python: 3.6
  - name: "Linux, 3.7, pip, doc"
    env: PIP_SELECTOR="all, build-doc"
    python: 3.7

before_install:
  # Clone the ci-scripts repo to get the ci setup scripts
  - git clone --depth 1 git://github.com/hyperspy/ci-scripts.git
  - source ci-scripts/travis/setup_travis.sh

install:
  # Because of https://github.com/pypa/pip/issues/4391, we need to update pytest
  # manually
  - pip install --upgrade pytest
  - if [ "$MINIMUM_VERSION" == true ]; then
      pip install matplotlib==2.2.3 numpy==1.14 scipy==1.0.1 numba==0.40;
      pip install -e .["${PIP_SELECTOR}"];
    else
      pip install --upgrade -e .["${PIP_SELECTOR}"];
    fi

script:
  - which python
  - python -c 'import matplotlib.pyplot as plt; print("Matplotlib backend:", plt.get_backend())';
  - if [[ $PIP_SELECTOR == *"build-doc"* ]]; then
      cd doc && make html;
    else
      echo "pytest arguments $PYTEST_ARGS";
      pytest $PYTEST_ARGS;
    fi

after_success:
  - if [[ $PYTEST_ARGS == *"--cov=hyperspy"* ]]; then
      codecov;
    fi
