language: python

sudo: false

python:
  - 3.5

env:
  - DEPS="nose numpy scipy matplotlib ipython h5py sympy scikit-learn natsort mock"

install:
  - conda create -n testenv --yes python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install --yes $DEPS
  - conda install pip
  - pip install coverage coveralls traits traitsui
  # The following two lines set hyperspy to run headless. This is a temporary
  # workaround until we fix hyperspy so that this is not required.
  - python setup.py install

before_install:
  # Does not matter which miniconda we get, we still create a virtualenv
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  # miniconda is not always up-to-date with conda.
  - conda update --yes conda
script: python continuous_integration/nosetest.py --with-coverage hyperspy
after_success:
    coveralls
