name: hyperspy
dependencies:
- python=3.5
- dill
- h5py
- ipython
- ipyparallel
- jupyter
- matplotlib
- nose
- numpy
- qt
- scikit-image
- scikit-learn
- scipy
- setuptools
- statsmodels
- sympy
- natsort
- ncurses
- requests
- pango
- pip:
  - dask
  - hyperspy
  - traits
  - traitsui
  - tqdm
  - ipywidgets
  - tqdm
