name: test_env
channels:
- conda-forge
dependencies:
- dask-core >=2.11
- dill
# dask-core < 2021.3.1 doesn't have fsspec as dependency
- fsspec
- importlib-metadata
- ipyparallel
- ipython !=8.0.*
- jinja2
- matplotlib-base
- natsort
- numba
- numexpr
- numpy
- packaging
- pint
- prettytable
- python-dateutil
- pyyaml
- requests
- scikit-image
- scikit-learn
- scipy
- sympy
- tqdm
- traits
