[build-system]
requires = ["setuptools>=40.8.0", "wheel", "cython"]
build-backend = "setuptools.build_meta:__legacy__"


[tool.towncrier]
package = "hyperspy"
filename = "CHANGES.rst"
directory = "upcoming_changes/"
title_format = "v{version} ({project_date})"
issue_format = "`#{issue} <https://github.com/hyperspy/hyperspy/issues/{issue}>`_"

  [[tool.towncrier.type]]
  directory = "feature"
  name = "Features"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "bugfix"
  name = "Bug Fixes"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "doc"
  name = "Improved Documentation"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "deprecation"
  name = "Deprecations"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "improvement"
  name = "Improvements"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "breaking"
  name = "Breaking Changes"
  showcontent = true
