name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build_wheels:
    name: Wheels on ${{ matrix.os }}/py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - uses: docker://quay.io/pypa/manylinux2010_x86_64
        if: runner.os == 'Linux'

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: ${{ matrix.python-version }}

      - name: install pep517
        run: |
          python -m pip install --upgrade pip
          python -m pip install pep517 auditwheel

      - name: Install Visual C++ for Python 2.7
        if: runner.os == 'Windows'
        run: |
          choco install vcpython27 -f -y

      - name: Build wheels
        run: |
          python -m pep517.build --binary --out-dir dist/ .

      #- name: auditwheel
      #  if: runner.os == 'Linux'
      #  run: |
      #    auditwheel repair dist/*.whl

      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl
