name: Release

on: [push, pull_request]
#  push:
#    # Sequence of patterns matched against refs/tags
#    tags:
#    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build_wheels:
    name: Wheels on ${{ matrix.os }}/py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: ${{ matrix.python-version }}

      - name: What OS and Python version
        run: |
          uname -a
          python --version
          which python

      - name: Install Visual C++ for Python 2.7
        if: runner.os == 'Windows'
        run: |
          choco install vcpython27 -f -y

      - name: install pep517
        run: |
          python -m pip install --upgrade pip
          python -m pip install pep517 cython

      - name: Build wheels
        run: |
          python -m pep517.build --binary --out-dir dist/ .

      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl

  build_wheels_linux:
    name: Wheels on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build manylinux Python wheels
        uses: RalfG/python-wheels-manylinux-build@v0.3.1-manylinux2010_x86_64
        with:
          build-requirements: 'cython'

      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl
