name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]
        #python-version: [ '3.6', '3.7', '3.8' ]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: install pep517
        run: |
          python -m pip install --upgrade pip
          python -m pip install pep517

      - name: Install Visual C++ for Python 2.7
        if: runner.os == 'Windows'
        run: |
          choco install vcpython27 -f -y

      - name: Build wheels
        env:
          CIBW_BUILD: cp3*
        run: |
          python -m pep517.build --binary --out-dir dist/ .

      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl
