name: Release
# This workflow builds the wheels "on tag".
# If run from the hyperspy/hyperspy repository, the wheels will be uploaded to pypi ;
# otherwise, the wheels will be available as a github artifact.
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  create_release:
    permissions:
      contents: write
    name: Create Release
    runs-on: ubuntu-latest
    outputs: 
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844

  build_and_upload:
    name: Build wheel and sdist
    runs-on: ubuntu-latest
    needs: create_release

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        name: Install Python

      - name: What OS and Python version
        run: |
          uname -a
          python --version
          which python

      - name: install build and twine
        run: |
          python -m pip install build twine

      - name: Build wheels
        run: |
          python -m build

      - name: Display content dist folder
        run: |
          ls -shR dist/

      - name: Install and test distribution
        env:
          MPLBACKEND: agg
        run: |
          pip install --pre --find-links dist hyperspy[tests]
          pytest --pyargs hyperspy

      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*

      - name: Publish wheels to PyPI
        if: github.repository_owner == 'hyperspy'
        env:
          # Github secret set in the hyperspy/hyperspy repository
          # Not available from fork or pull request
          # Secrets are not passed to workflows that are triggered by a pull request from a fork
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload dist/* --verbose

      # Don't use the pypa publish action for now as we need to filter the `linux` wheels
      # With hyperspy 2.0, it will be noarch and the release workflow will refactor
      # - name: Publish wheels to PyPI
      #   if: github.repository_owner == 'hyperspy'
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     # Github secret set in the hyperspy/hyperspy repository
      #     # Not available from fork or pull request
      #     # Secrets are not passed to workflows that are triggered by a pull request from a fork
      #     password: ${{ secrets.PYPI_API_TOKEN }}
